"""Reusable Streamlit UI components."""

from __future__ import annotations

import html
import re

import streamlit as st

from ui.about_content import (
    FAQS,
    HERO_EYEBROW,
    HERO_LEAD,
    HERO_PILLARS,
    LIMITATIONS,
    MCP_TOOLS,
    PIPELINE_STEPS,
    ROADMAP,
)
from ui.placeholders import AgentTile, QuickStat

_AGENT_ICONS: dict[str, str] = {
    "price":   "📊",
    "options": "📉",
    "news":    "📰",
    "macro":   "🌐",
    "events":  "📅",
    "analyst": "🎯",
    "sector":  "🏭",
}

_PERIODS = ["1W", "1M", "6M", "YTD", "1Y"]


# ── Markdown → HTML ──────────────────────────────────────────────────────────

def _md_to_html(text: str) -> str:
    lines = text.split("\n")
    out: list[str] = []
    in_list: str | None = None

    def close_list() -> None:
        nonlocal in_list
        if in_list:
            out.append(f"</{in_list}>")
            in_list = None

    def fmt(s: str) -> str:
        s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
        s = re.sub(r"_([^_\n]+)_", r"<em>\1</em>", s)
        s = re.sub(r"(?<!\*)\*([^*\n]+)\*(?!\*)", r"<em>\1</em>", s)
        return s

    for line in lines:
        stripped = line.strip()
        if not stripped:
            close_list()
            continue
        # Escape BEFORE any markdown-marker parsing below — this text is LLM-authored
        # (ultimately sourced from external news headlines an attacker could influence),
        # so any literal <, >, & must become inert entities before we ever interpolate it
        # into HTML. html.escape() doesn't touch *, _, #, -, digits, so the markdown
        # detection/formatting below (which only cares about those characters) still works
        # on the escaped text; fmt() then only ever adds tags we control ourselves.
        stripped = html.escape(stripped)

        m = re.match(r"^(\d+)\.\s+(.+)$", stripped)
        if m:
            if in_list == "ul":
                close_list()
            if not in_list:
                out.append('<ol class="analysis-list" style="margin:0.5rem 0 0.75rem 1.4rem;padding:0;">')
                in_list = "ol"
            # Explicit value= — the evidence/caveat lines below each hypothesis title aren't
            # list items themselves, so they close this <ol> right after one <li>. Without
            # value=, a lone <li> always displays "1." regardless of the source number.
            out.append(f'<li value="{m.group(1)}" style="margin-bottom:0.5rem;font-size:0.88rem;line-height:1.7;color:#0F172A;">{fmt(m.group(2))}</li>')
            continue

        m2 = re.match(r"^[-•]\s+(.+)$", stripped)
        if m2:
            if in_list == "ol":
                close_list()
            if not in_list:
                out.append('<ul class="analysis-list" style="margin:0.5rem 0 0.75rem 1.4rem;padding:0;">')
                in_list = "ul"
            out.append(f'<li style="margin-bottom:0.5rem;font-size:0.88rem;line-height:1.7;color:#0F172A;">{fmt(m2.group(1))}</li>')
            continue

        close_list()

        m3 = re.match(r"^(#{1,4})\s+(.+)$", stripped)
        if m3:
            out.append(
                f'<p style="font-weight:700;font-size:0.95rem;color:#0F172A;'
                f'margin:0.9rem 0 0.3rem;letter-spacing:-0.015em;">{fmt(m3.group(2))}</p>'
            )
            continue

        out.append(
            f'<p style="font-size:0.88rem;line-height:1.8;color:#334155;margin:0 0 0.6rem 0;">{fmt(stripped)}</p>'
        )

    close_list()
    return "\n".join(out)


# ── Ticker autocomplete ───────────────────────────────────────────────────────

# ── Components ────────────────────────────────────────────────────────────────

def render_footer() -> None:
    st.markdown(
        '<div class="app-footer">'
        '<p class="footer-disclaimer">'
        '<strong>Not financial advice.</strong> Agentic Market Explainer is an '
        'informational and educational tool only. It does not provide investment, '
        'legal, or tax advice, and nothing shown here should be treated as a '
        'recommendation to buy, sell, or hold any security. Analysis is generated by '
        'an AI system that synthesizes publicly available market data and news to '
        '<strong>describe</strong> — not predict — recent price action; like any AI '
        'system, it can be incomplete, out of date, or simply wrong ("hallucinate"), '
        'so verify anything important against a primary source before acting on it. '
        'Past performance is not indicative of future results. Always consult a '
        'licensed financial advisor before making investment decisions.'
        '</p>'
        '<div class="footer-bottom">'
        '<span class="footer-meta">© 2026 Agentic Market Explainer · Data via Finnhub, '
        'yfinance &amp; FRED · Analysis by Claude</span>'
        '<span class="footer-actions">'
        '<a class="footer-github" href="https://github.com/Sakthibats/Agentic-VolatilityExplainer" '
        'target="_blank" rel="noopener" aria-label="View source on GitHub" title="View source on GitHub">'
        '<svg viewBox="0 0 16 16" aria-hidden="true">'
        '<path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 '
        '0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 '
        '1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 '
        '0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 '
        '2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 '
        '3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z"/>'
        '</svg></a>'
        '<a class="footer-feedback-pill" href="mailto:hello@market-explainer.com'
        '?subject=Agentic%20Market%20Explainer%20%E2%80%94%20Feedback'
        '&amp;body=Hi%20MarketExplainer%20Team%2C%0A%0A'
        'Type%20(bug%20%2F%20feedback%20%2F%20suggestion%20%2F%20other)%3A%20%0A%0A'
        'What%20happened%20or%20what%20would%20you%20like%20to%20see%3F%3A%0A%0A'
        'Thanks!">'
        '🐛 Found a bug? Got an idea?</a>'
        '</span>'
        '</div>'
        '</div>',
        unsafe_allow_html=True,
    )


def _go_home() -> None:
    st.session_state["view"] = "main"


def _go_about() -> None:
    st.session_state["view"] = "about"


def render_brand_header() -> None:
    """Brand block, Beta tag, and the Home/About nav — one row, same header bar.

    Deliberately st.button, not a real `<a href="?view=...">` — an anchor tag navigates
    the browser (full document reload, session re-init flash) even for a same-page query
    string change. A widget click only triggers Streamlit's normal script-rerun-over-the-
    existing-WebSocket path, which never reloads the page. The buttons are reset with
    `all: unset` in theme.py and re-skinned as a pill nav so they don't look like buttons."""
    view = st.session_state.get("view", "main")
    with st.container(key="app_header_row"):
        col_brand, col_tag, col_nav = st.columns(
            [8, 1, 1.5], gap="small", vertical_alignment="center"
        )
        with col_brand:
            st.markdown(
                '<div class="header-brand">'
                '<div class="header-logo">AME</div>'
                '<div>'
                '<span class="header-title">Agentic Market Explainer</span>'
                '<span class="header-sub">AI investigates why any stock or market moved — multi-agent analysis</span>'
                '</div>'
                '</div>',
                unsafe_allow_html=True,
            )
        with col_tag:
            st.markdown(
                '<div class="header-tag-wrap"><span class="header-tag">Beta</span></div>',
                unsafe_allow_html=True,
            )
        with col_nav:
            # Nested container gives the pair a shared pill "track" background (the
            # segmented-control look) — two bare st.button widgets side by side have no
            # single element to hang that background/border on.
            with st.container(key="nav_group"):
                col_home, col_about = st.columns([1, 1], gap="small")
                with col_home:
                    st.button(
                        "Home",
                        key="nav_home",
                        type="primary" if view == "main" else "secondary",
                        on_click=_go_home,
                    )
                with col_about:
                    st.button(
                        "About",
                        key="nav_about",
                        type="primary" if view == "about" else "secondary",
                        on_click=_go_about,
                    )


def _start_analysis() -> None:
    query = st.session_state.get("search_input", "").strip()
    if query:
        st.session_state["submitted_query"] = query
        st.session_state["analysis_phase"] = "running"
        st.session_state["visible_tiles"] = 0
        st.session_state["analysis_result"] = None
        st.session_state["all_tiles"] = []


def _stop_analysis() -> None:
    st.session_state["analysis_phase"] = "stopped"


def render_search_bar() -> str:
    # Callbacks (on_click) run *before* the script reruns, so session_state
    # already reflects the click by the time the button label below is
    # computed — a plain `if submitted:` check after the fact would only
    # update the label on the following rerun (i.e. the next click).
    is_running = st.session_state.get("analysis_phase") == "running"

    # st.form gives us a real DOM container we can style as a card via CSS.
    # A custom <div> wrapper around st.columns() doesn't work — Streamlit
    # renders its own column containers outside any preceding markdown div.
    with st.form(key="search_form", clear_on_submit=False, border=False):
        col_input, col_btn = st.columns([8, 1], gap="small", vertical_alignment="center")
        with col_input:
            query = st.text_input(
                "Search",
                placeholder="Try: TSLA · why did Tesla dip? · what happened to gold? · market down?",
                label_visibility="collapsed",
                key="search_input",
                disabled=is_running,
                autocomplete="off",
            )
        with col_btn:
            if is_running:
                st.form_submit_button(
                    "Stop",
                    type="primary",
                    width="stretch",
                    on_click=_stop_analysis,
                )
            else:
                st.form_submit_button(
                    "Analyze →",
                    type="primary",
                    width="stretch",
                    on_click=_start_analysis,
                )

    return query


def render_guardrail_error(message: str) -> None:
    # message can be LLM-authored (the guardrail JSON's "message" field) — escape before
    # interpolating into raw HTML.
    st.markdown('<p class="panel-label">Analysis</p>', unsafe_allow_html=True)
    st.markdown(
        f'<div class="guardrail-box">'
        f'<div class="guardrail-icon">🚫</div>'
        f'<div class="guardrail-title">Out of scope</div>'
        f'<div class="guardrail-body">{html.escape(message)}</div>'
        f'</div>',
        unsafe_allow_html=True,
    )


def render_thinking_step(placeholder, label: str) -> None:
    """Update a st.empty() placeholder with the current investigation step."""
    placeholder.markdown(
        f'<div class="analysis-box thinking">'
        f'<div class="thinking-label">{label}'
        f'<span class="thinking-dots"><span>·</span><span>·</span><span>·</span></span>'
        f'</div>'
        f'<div class="shimmer-bar w80"></div>'
        f'<div class="shimmer-bar w60"></div>'
        f'<div class="shimmer-bar w45"></div>'
        f'<div class="shimmer-bar w80" style="margin-top:0.5rem;"></div>'
        f'<div class="shimmer-bar w60"></div>'
        f'</div>',
        unsafe_allow_html=True,
    )


def render_final_output_box(*, thinking: bool, content: str | None = None) -> None:
    st.markdown('<p class="panel-label">Analysis</p>', unsafe_allow_html=True)

    if thinking:
        st.markdown(
            '<div class="analysis-box thinking">'
            '<div class="thinking-label">Investigating price action'
            '<span class="thinking-dots"><span>·</span><span>·</span><span>·</span></span>'
            '</div>'
            '<div class="shimmer-bar w80"></div>'
            '<div class="shimmer-bar w60"></div>'
            '<div class="shimmer-bar w45"></div>'
            '<div class="shimmer-bar w80" style="margin-top:0.5rem;"></div>'
            '<div class="shimmer-bar w60"></div>'
            '</div>',
            unsafe_allow_html=True,
        )
    elif content:
        body_html = _md_to_html(content)
        st.markdown(
            f'<div class="analysis-box complete">'
            f'<div class="analysis-content">{body_html}</div>'
            f'</div>',
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            '<div class="analysis-box empty-panel">'
            '<div class="empty-state">'
            '<span class="empty-icon">🔍</span>'
            '<span class="empty-title">Start an investigation</span>'
            'Enter a ticker, company name, or ask a question.<br>'
            '<span class="empty-hint">Try: <em>why did AAPL dip?</em> or <em>what happened to gold?</em></span>'
            '</div>'
            '</div>',
            unsafe_allow_html=True,
        )


def render_agent_tile(tile: AgentTile) -> None:
    # tile.title/summary/reasoning are LLM-authored (ultimately derived from external news
    # headlines an attacker could influence) — escape before interpolating into raw HTML.
    icon = _AGENT_ICONS.get(tile.agent, "🔍")
    title = html.escape(tile.title)
    summary = html.escape(tile.summary)
    reasoning_html = (
        f'<p style="font-size:0.72rem;color:#64748B;font-style:italic;'
        f'margin:0 0 0.45rem 0;line-height:1.5;">→ {html.escape(tile.reasoning)}</p>'
        if tile.reasoning
        else ""
    )
    citations_html = ""
    if tile.citations:
        pills = "".join(
            f'<a class="citation-pill" href="{html.escape(c.url)}" target="_blank" '
            f'rel="noopener noreferrer" title="{html.escape(c.source)}">{c.number}</a>'
            for c in tile.citations
        )
        citations_html = f'<div class="citations-row">{pills}</div>'
    st.markdown(
        f'<div class="agent-tile">'
        f'{reasoning_html}'
        f'<div class="tile-header">'
        f'<span class="tile-title">{icon}&nbsp;{title}</span>'
        f'</div>'
        f'<p class="tile-body">{summary}</p>'
        f'{citations_html}'
        f'</div>',
        unsafe_allow_html=True,
    )


def render_agent_tiles_section(tiles: list[AgentTile], visible_count: int) -> None:
    if not tiles and visible_count == 0:
        return
    st.markdown('<p class="section-label">Agent findings</p>', unsafe_allow_html=True)
    for tile in tiles[:visible_count]:
        render_agent_tile(tile)


def render_price_chart(ticker: str) -> None:
    import plotly.graph_objects as go

    period = st.session_state.get("chart_period", "6M")

    st.markdown(
        f'<p class="panel-label" style="margin-bottom:0.4rem;">{ticker} · Price</p>',
        unsafe_allow_html=True,
    )

    # Period selector — keyed container so CSS can render the five buttons as one
    # compact segmented row that sizes to content and never wraps ("YT / D") on
    # narrow viewports, instead of five full-width columns.
    with st.container(key="chart_periods"):
        cols = st.columns(len(_PERIODS))
        for i, p in enumerate(_PERIODS):
            with cols[i]:
                is_active = period == p
                if st.button(p, key=f"period_{p}", type="primary" if is_active else "secondary", width="stretch"):
                    st.session_state["chart_period"] = p
                    st.rerun()

    from ui.placeholders import fetch_price_history
    df = fetch_price_history(ticker, period)

    if df.empty:
        st.markdown('<p style="color:#94A3B8;font-size:0.8rem;padding:1rem 0;">No price data available.</p>', unsafe_allow_html=True)
        return

    y_min = df["close"].min()
    y_max = df["close"].max()
    padding = max((y_max - y_min) * 0.1, y_max * 0.02)
    y_lo = y_min - padding
    y_hi = y_max + padding

    net_change = df["close"].iloc[-1] - df["close"].iloc[0]
    if net_change >= 0:
        line_color, fill_color = "#16A34A", "rgba(22,163,74,0.07)"
    else:
        line_color, fill_color = "#DC2626", "rgba(220,38,38,0.07)"

    tick_fmt = "%b %d" if period in ("1W", "1M") else "%b" if period in ("YTD", "6M") else "%b '%y"

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=df["date"],
        y=df["close"],
        mode="lines",
        line=dict(color=line_color, width=1.8),
        fill="tozeroy",
        fillcolor=fill_color,
        hovertemplate="<b>%{x|%b %d, %Y}</b><br>$%{y:,.2f}<extra></extra>",
    ))

    fig.update_layout(
        margin=dict(l=0, r=0, t=4, b=0),
        height=200,
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        xaxis=dict(
            showgrid=False,
            showline=False,
            tickfont=dict(family="Inter, -apple-system, sans-serif", size=9.5, color="#94A3B8"),
            tickformat=tick_fmt,
            nticks=5,
        ),
        yaxis=dict(
            range=[y_lo, y_hi],
            showgrid=True,
            gridcolor="rgba(15,23,42,0.05)",
            gridwidth=1,
            showline=False,
            tickfont=dict(family="Inter, -apple-system, sans-serif", size=9.5, color="#94A3B8"),
            tickprefix="$",
            tickformat=",.0f",
            nticks=4,
            side="right",
        ),
        hovermode="x unified",
        font=dict(family="Inter, -apple-system, sans-serif"),
        hoverlabel=dict(
            bgcolor="white",
            bordercolor="rgba(15,23,42,0.1)",
            font=dict(family="Inter, -apple-system, sans-serif", size=12),
        ),
    )

    st.plotly_chart(fig, width="stretch", config={"displayModeBar": False})


def render_quick_stats(stats: list[QuickStat], title: str = "Quick stats") -> None:
    st.markdown(f'<p class="section-label" style="margin-top:0.6rem;">{title}</p>', unsafe_allow_html=True)
    cards: list[str] = []
    for stat in stats:
        if stat.delta:
            css = "pos" if stat.delta.startswith("+") else ("neg" if stat.delta.startswith("-") else "neu")
            delta_html = f'<div class="stat-delta {css}">{stat.delta}</div>'
        else:
            delta_html = ""
        cards.append(
            f'<div class="stat-card">'
            f'<div class="stat-label">{stat.label}</div>'
            f'<div class="stat-value">{stat.value}</div>'
            f'{delta_html}'
            f'</div>'
        )
    st.markdown(f'<div class="stat-grid">{"".join(cards)}</div>', unsafe_allow_html=True)


def render_right_panel(ticker: str | None) -> None:
    if not ticker:
        st.markdown('<p class="panel-label">Price</p>', unsafe_allow_html=True)
        st.markdown(
            '<div class="analysis-box empty-panel" style="min-height:300px;">'
            '<div class="empty-state">'
            '<span class="empty-icon">📈</span>'
            '<span class="empty-title">Price chart</span>'
            'Chart and stats will appear<br>once you analyze a ticker.'
            '</div>'
            '</div>',
            unsafe_allow_html=True,
        )
    else:
        from ui.placeholders import fetch_analyst_stats, fetch_quick_stats
        render_price_chart(ticker)
        render_quick_stats(fetch_quick_stats(ticker))
        render_quick_stats(fetch_analyst_stats(ticker), title="Analyst targets")


def render_ticker_chip(ticker: str) -> None:
    st.markdown(
        f'<div class="ticker-chip">▲&nbsp;{ticker}</div>',
        unsafe_allow_html=True,
    )


def render_about_page() -> None:
    """Static About page: how the app works, the MCP tool surface, FAQs, limitations,
    and what's next. Content lives in ui/about_content.py — edit that file (by hand, or
    an LLM-drafted pass you verify) rather than this render function."""
    pillar_cards = "".join(
        f'<div class="about-pillar-card">'
        f'<span class="about-pillar-icon">{p.icon}</span>'
        f'<div class="about-pillar-title">{p.title}</div>'
        f'<p class="about-pillar-body">{p.body}</p>'
        f'</div>'
        for p in HERO_PILLARS
    )
    st.markdown(
        '<div class="about-hero">'
        f'<p class="about-hero-eyebrow">{HERO_EYEBROW}</p>'
        '<p class="about-hero-title">How Agentic Market Explainer works</p>'
        f'<p class="about-hero-sub">{HERO_LEAD}</p>'
        f'<div class="about-pillar-grid">{pillar_cards}</div>'
        '</div>',
        unsafe_allow_html=True,
    )

    st.markdown('<p class="about-section-title">Pipeline</p>', unsafe_allow_html=True)
    for step in PIPELINE_STEPS:
        st.markdown(
            f'<div class="about-step">'
            f'<div class="about-step-icon">{step.icon}</div>'
            f'<div>'
            f'<div class="about-step-title">{step.title}</div>'
            f'<p class="about-step-body">{step.body}</p>'
            f'</div>'
            f'</div>',
            unsafe_allow_html=True,
        )

    st.markdown('<p class="about-section-title">MCP tools</p>', unsafe_allow_html=True)
    cards = "".join(
        f'<div class="about-tool-card">'
        f'<div class="about-tool-head">'
        f'<span>{tool.icon}</span>'
        f'<span class="about-tool-name">{tool.name}</span>'
        f'<span class="about-tool-module">{tool.module}</span>'
        f'</div>'
        f'<p class="about-tool-desc">{tool.description}</p>'
        f'</div>'
        for tool in MCP_TOOLS
    )
    st.markdown(f'<div class="about-tool-grid">{cards}</div>', unsafe_allow_html=True)

    st.markdown('<p class="about-section-title">FAQs</p>', unsafe_allow_html=True)
    for faq in FAQS:
        with st.expander(faq.question):
            st.markdown(f'<p class="about-step-body">{faq.answer}</p>', unsafe_allow_html=True)

    st.markdown('<p class="about-section-title">Limitations</p>', unsafe_allow_html=True)
    items = "".join(f"<li>{item}</li>" for item in LIMITATIONS)
    st.markdown(f'<ul class="about-limitations">{items}</ul>', unsafe_allow_html=True)

    st.markdown('<p class="about-section-title">On the roadmap</p>', unsafe_allow_html=True)
    for item in ROADMAP:
        st.markdown(
            f'<div class="roadmap-card">'
            f'<span class="roadmap-badge {item.status}">{item.status.replace("-", " ")}</span>'
            f'<div>'
            f'<div class="roadmap-title">{item.title}</div>'
            f'<p class="roadmap-body">{item.body}</p>'
            f'</div>'
            f'</div>',
            unsafe_allow_html=True,
        )
