import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Link from "next/link";
import { ThemeProvider } from "next-themes";

import { ThemeToggle } from "@/components/theme-toggle";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Agentic Market Explainer",
  description:
    "Ask why a stock moved and get a real investigation — live data, ranked hypotheses, traceable sources.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} h-full antialiased`}
    >
      <body className="flex min-h-screen flex-col">
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
          <header className="sticky top-0 z-10 border-b border-black/5 bg-background/75 backdrop-blur-md dark:border-white/5">
            <div className="mx-auto flex h-16 max-w-5xl items-center gap-3 px-4">
              <Link href="/" className="flex items-center gap-3">
                <span className="gradient-tile flex size-9 items-center justify-center rounded-xl text-[11px] font-bold tracking-wide text-[#f5f8fc]">
                  AME
                </span>
                <span className="hidden flex-col sm:flex">
                  <span className="text-sm font-semibold tracking-tight">
                    Agentic <span className="gradient-wordmark">Market Explainer</span>
                  </span>
                  <span className="text-[11px] text-muted-foreground">
                    AI investigates why any stock or market moved
                  </span>
                </span>
                <span className="text-sm font-semibold tracking-tight sm:hidden">
                  Agentic <span className="gradient-wordmark">ME</span>
                </span>
              </Link>
              <span className="rounded-full border border-primary/25 bg-accent px-2 py-0.5 text-[10px] font-semibold tracking-widest text-primary">
                BETA
              </span>
              <nav className="ml-auto flex items-center gap-1 rounded-full border bg-card p-1 shadow-sm">
                <Link
                  href="/"
                  className="rounded-full px-3.5 py-1.5 text-sm font-medium transition-colors hover:bg-accent"
                >
                  Home
                </Link>
                <Link
                  href="/about"
                  className="rounded-full px-3.5 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground"
                >
                  About
                </Link>
              </nav>
              <ThemeToggle />
            </div>
          </header>
          <main className="mx-auto w-full max-w-5xl flex-1 px-4 py-6">{children}</main>
          <footer className="mt-10 border-t">
            <div className="mx-auto max-w-5xl space-y-5 px-4 py-6">
              {/* Legal coverage is preserved in full — just no longer the largest
                  text block on the page. */}
              <details className="group text-[13px] text-muted-foreground">
                <summary className="cursor-pointer list-none [&::-webkit-details-marker]:hidden">
                  <span className="font-semibold text-foreground">
                    Not financial advice.
                  </span>{" "}
                  AI-generated analysis may be wrong.{" "}
                  <span className="text-primary underline-offset-2 group-hover:underline">
                    Read full disclaimer
                  </span>
                </summary>
                <p className="mt-3 max-w-3xl leading-relaxed">
                  Agentic Market Explainer is an informational and educational tool
                  only. It does not provide investment, legal, or tax advice, and
                  nothing shown here should be treated as a recommendation to buy,
                  sell, or hold any security. Analysis is generated by an AI system
                  that synthesizes publicly available market data and news to{" "}
                  <span className="font-semibold">describe</span> — not predict —
                  recent price action; like any AI system, it can be incomplete, out of
                  date, or simply wrong (&ldquo;hallucinate&rdquo;), so verify anything
                  important against a primary source before acting on it. Past
                  performance is not indicative of future results. Always consult a
                  licensed financial advisor before making investment decisions.
                </p>
              </details>
              <div className="flex flex-wrap items-center justify-between gap-x-4 gap-y-2 text-xs text-muted-foreground">
                <span>
                  © {new Date().getFullYear()}{" "}
                  Agentic Market Explainer · Data via Finnhub, yfinance &amp; FRED ·
                  Analysis by Claude
                </span>
                {/* Grid (not flex) so both pills are always exactly equal width,
                    at any viewport: stacked full-width on phones, side by side above. */}
                <span className="grid w-full grid-cols-1 gap-2 sm:w-auto sm:grid-cols-2">
                  <a
                    href="https://buymeacoffee.com/sakthibats"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="pill-action flex min-h-10 items-center justify-center gap-1.5 rounded-full border px-4 py-2 text-center font-medium text-muted-foreground"
                  >
                    <span aria-hidden>☕</span> Buy me a coffee
                  </a>
                  <a
                    href={`mailto:hello@market-explainer.com?subject=${encodeURIComponent(
                      "Agentic Market Explainer — Feedback",
                    )}&body=${encodeURIComponent(
                      "Hi MarketExplainer Team,\n\nType (bug / feedback / suggestion / other): \n\nWhat happened or what would you like to see?: \n\nThanks!",
                    )}`}
                    className="pill-action flex min-h-10 items-center justify-center gap-1.5 rounded-full border px-4 py-2 text-center font-medium text-muted-foreground"
                  >
                    <span aria-hidden>🐛</span> Found a bug? Got an idea?
                  </a>
                </span>
              </div>
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
