/* ARCHIVED color schemes — not imported anywhere; parked for the future
   user-profile theme-preference feature.

   Decision (2026-07-27): Cobalt is the brand default, baked into
   frontend/app/globals.css (:root = light, .dark = dark). The alternates below
   (Sky, Indigo + wildcards) are ready-made token sets for when users can pick
   their own theme: drop this file back into frontend/lib/, apply a scheme by
   injecting schemeCss() into a <style> tag (see git history of
   frontend/app/lab/page.tsx for the working switcher implementation). */

export interface SchemeTokens {
  background: string;
  card: string;
  primary: string;
  "primary-foreground": string;
  secondary: string;
  muted: string;
  "muted-foreground": string;
  accent: string;
  "accent-foreground": string;
  border: string;
  input: string;
  ring: string;
  "chart-line": string;
  "chart-fill": string;
  "chart-grid": string;
}

export interface Scheme {
  name: string;
  note: string;
  light: SchemeTokens;
  dark: SchemeTokens;
}

const cobaltDark: SchemeTokens = {
  background: "#0b1220",
  card: "#0f1729",
  primary: "#4b9fea",
  "primary-foreground": "#0b1220",
  secondary: "#111c2e",
  muted: "#111c2e",
  "muted-foreground": "#8da2b8",
  accent: "#13233a",
  "accent-foreground": "#9ec9f5",
  border: "#1e293b",
  input: "#1e293b",
  ring: "#4b9fea",
  "chart-line": "#4b9fea",
  "chart-fill": "rgba(75, 159, 234, 0.1)",
  "chart-grid": "#16223a",
};

export const SCHEMES: Scheme[] = [
  {
    name: "Cobalt",
    note: "Current default — brand #1565C0 on blue-tinted off-white",
    light: {
      background: "#f4f6fb",
      card: "#ffffff",
      primary: "#1565c0",
      "primary-foreground": "#ffffff",
      secondary: "#f1f5f9",
      muted: "#f1f5f9",
      "muted-foreground": "#64748b",
      accent: "#e3f2fd",
      "accent-foreground": "#0d47a1",
      border: "#e6ebf2",
      input: "#e6ebf2",
      ring: "#1976d2",
      "chart-line": "#1565c0",
      "chart-fill": "rgba(21, 101, 192, 0.08)",
      "chart-grid": "#eef2f7",
    },
    dark: cobaltDark,
  },
  {
    name: "Sky",
    note: "Lighter, airier blue — cooler canvas, sky-600 accents",
    light: {
      background: "#f2f7fc",
      card: "#ffffff",
      primary: "#0284c7",
      "primary-foreground": "#ffffff",
      secondary: "#eef4f9",
      muted: "#eef4f9",
      "muted-foreground": "#5b7285",
      accent: "#e0f2fe",
      "accent-foreground": "#075985",
      border: "#e2ecf4",
      input: "#e2ecf4",
      ring: "#0ea5e9",
      "chart-line": "#0284c7",
      "chart-fill": "rgba(2, 132, 199, 0.08)",
      "chart-grid": "#eaf3f9",
    },
    dark: {
      ...cobaltDark,
      background: "#081420",
      card: "#0c1b2a",
      primary: "#38bdf8",
      accent: "#0e2438",
      "accent-foreground": "#7dd3fc",
      ring: "#38bdf8",
      "chart-line": "#38bdf8",
      "chart-fill": "rgba(56, 189, 248, 0.1)",
    },
  },
  {
    name: "Indigo",
    note: "Deeper, more 'product-y' — indigo-600, violet-tinted canvas",
    light: {
      background: "#f5f5fc",
      card: "#ffffff",
      primary: "#4f46e5",
      "primary-foreground": "#ffffff",
      secondary: "#f1f1f9",
      muted: "#f1f1f9",
      "muted-foreground": "#6b7089",
      accent: "#e8e7fd",
      "accent-foreground": "#3730a3",
      border: "#e8e8f3",
      input: "#e8e8f3",
      ring: "#6366f1",
      "chart-line": "#4f46e5",
      "chart-fill": "rgba(79, 70, 229, 0.08)",
      "chart-grid": "#efeff8",
    },
    dark: {
      ...cobaltDark,
      background: "#0d0f1e",
      card: "#131629",
      primary: "#818cf8",
      accent: "#1b1f3d",
      "accent-foreground": "#a5b4fc",
      border: "#232748",
      input: "#232748",
      ring: "#818cf8",
      "chart-line": "#818cf8",
      "chart-fill": "rgba(129, 140, 248, 0.1)",
      "chart-grid": "#1a1e38",
    },
  },
  {
    name: "Teal (wildcard)",
    note: "Off-brand experiment — teal-600, sea-glass canvas",
    light: {
      background: "#f2faf9",
      card: "#ffffff",
      primary: "#0d9488",
      "primary-foreground": "#ffffff",
      secondary: "#edf6f5",
      muted: "#edf6f5",
      "muted-foreground": "#5c7672",
      accent: "#ccfbf1",
      "accent-foreground": "#115e59",
      border: "#e0efed",
      input: "#e0efed",
      ring: "#14b8a6",
      "chart-line": "#0d9488",
      "chart-fill": "rgba(13, 148, 136, 0.08)",
      "chart-grid": "#e9f5f3",
    },
    dark: {
      ...cobaltDark,
      background: "#081615",
      card: "#0c1f1d",
      primary: "#2dd4bf",
      "primary-foreground": "#081615",
      accent: "#10312d",
      "accent-foreground": "#5eead4",
      border: "#1c3d39",
      input: "#1c3d39",
      ring: "#2dd4bf",
      "chart-line": "#2dd4bf",
      "chart-fill": "rgba(45, 212, 191, 0.1)",
      "chart-grid": "#122b28",
    },
  },
  {
    name: "Graphite (wildcard)",
    note: "Near-monochrome slate — color only where data demands it",
    light: {
      background: "#f5f6f8",
      card: "#ffffff",
      primary: "#334155",
      "primary-foreground": "#ffffff",
      secondary: "#f0f1f4",
      muted: "#f0f1f4",
      "muted-foreground": "#6b7280",
      accent: "#e8eaef",
      "accent-foreground": "#1e293b",
      border: "#e5e7ec",
      input: "#e5e7ec",
      ring: "#475569",
      "chart-line": "#334155",
      "chart-fill": "rgba(51, 65, 85, 0.07)",
      "chart-grid": "#eef0f3",
    },
    dark: {
      ...cobaltDark,
      background: "#0c0e12",
      card: "#14171d",
      primary: "#94a3b8",
      "primary-foreground": "#0c0e12",
      accent: "#1d222b",
      "accent-foreground": "#cbd5e1",
      border: "#252a34",
      input: "#252a34",
      ring: "#94a3b8",
      "chart-line": "#94a3b8",
      "chart-fill": "rgba(148, 163, 184, 0.1)",
      "chart-grid": "#1b1f27",
    },
  },
];

SCHEMES.push(
  {
    name: "Amethyst (wildcard)",
    note: "Violet-forward — soft lavender canvas, purple-600 accents",
    light: {
      background: "#f7f5fc",
      card: "#ffffff",
      primary: "#7c3aed",
      "primary-foreground": "#ffffff",
      secondary: "#f3f0fa",
      muted: "#f3f0fa",
      "muted-foreground": "#6f6a85",
      accent: "#ede9fe",
      "accent-foreground": "#5b21b6",
      border: "#eae6f4",
      input: "#eae6f4",
      ring: "#8b5cf6",
      "chart-line": "#7c3aed",
      "chart-fill": "rgba(124, 58, 237, 0.08)",
      "chart-grid": "#f1eef8",
    },
    dark: {
      ...cobaltDark,
      background: "#100c1d",
      card: "#171228",
      primary: "#a78bfa",
      "primary-foreground": "#100c1d",
      accent: "#241b3f",
      "accent-foreground": "#c4b5fd",
      border: "#2b2347",
      input: "#2b2347",
      ring: "#a78bfa",
      "chart-line": "#a78bfa",
      "chart-fill": "rgba(167, 139, 250, 0.1)",
      "chart-grid": "#1e1836",
    },
  },
  {
    name: "Emerald (wildcard)",
    note: "Money-green — fresh mint canvas, emerald-600 accents",
    light: {
      background: "#f2faf5",
      card: "#ffffff",
      primary: "#059669",
      "primary-foreground": "#ffffff",
      secondary: "#edf6f1",
      muted: "#edf6f1",
      "muted-foreground": "#5e7469",
      accent: "#d1fae5",
      "accent-foreground": "#065f46",
      border: "#e1efe7",
      input: "#e1efe7",
      ring: "#10b981",
      "chart-line": "#059669",
      "chart-fill": "rgba(5, 150, 105, 0.08)",
      "chart-grid": "#eaf5ef",
    },
    dark: {
      ...cobaltDark,
      background: "#08150f",
      card: "#0d1f16",
      primary: "#34d399",
      "primary-foreground": "#08150f",
      accent: "#123227",
      "accent-foreground": "#6ee7b7",
      border: "#1c3b2e",
      input: "#1c3b2e",
      ring: "#34d399",
      "chart-line": "#34d399",
      "chart-fill": "rgba(52, 211, 153, 0.1)",
      "chart-grid": "#122b21",
    },
  },
  {
    name: "Sandstone (wildcard)",
    note: "Warm & editorial — cream paper canvas, ink text, amber accents",
    light: {
      background: "#faf7f2",
      card: "#ffffff",
      primary: "#b45309",
      "primary-foreground": "#ffffff",
      secondary: "#f5f1ea",
      muted: "#f5f1ea",
      "muted-foreground": "#78716c",
      accent: "#fef3c7",
      "accent-foreground": "#92400e",
      border: "#eee9e0",
      input: "#eee9e0",
      ring: "#d97706",
      "chart-line": "#b45309",
      "chart-fill": "rgba(180, 83, 9, 0.07)",
      "chart-grid": "#f3efe7",
    },
    dark: {
      ...cobaltDark,
      background: "#161210",
      card: "#1f1a16",
      primary: "#fbbf24",
      "primary-foreground": "#161210",
      "muted-foreground": "#a89f94",
      accent: "#33281a",
      "accent-foreground": "#fcd34d",
      border: "#3a322a",
      input: "#3a322a",
      ring: "#fbbf24",
      "chart-line": "#fbbf24",
      "chart-fill": "rgba(251, 191, 36, 0.09)",
      "chart-grid": "#2a2420",
    },
  },
  {
    name: "Crimson (wildcard)",
    note: "Bold contrarian — blush canvas, rose-600 accents",
    light: {
      background: "#fcf5f6",
      card: "#ffffff",
      primary: "#e11d48",
      "primary-foreground": "#ffffff",
      secondary: "#f9f0f2",
      muted: "#f9f0f2",
      "muted-foreground": "#7d6a6f",
      accent: "#ffe4e6",
      "accent-foreground": "#9f1239",
      border: "#f3e5e8",
      input: "#f3e5e8",
      ring: "#f43f5e",
      "chart-line": "#e11d48",
      "chart-fill": "rgba(225, 29, 72, 0.07)",
      "chart-grid": "#f8edef",
    },
    dark: {
      ...cobaltDark,
      background: "#180b0f",
      card: "#221118",
      primary: "#fb7185",
      "primary-foreground": "#180b0f",
      accent: "#3d1a26",
      "accent-foreground": "#fda4af",
      border: "#44222e",
      input: "#44222e",
      ring: "#fb7185",
      "chart-line": "#fb7185",
      "chart-fill": "rgba(251, 113, 133, 0.09)",
      "chart-grid": "#2f1720",
    },
  },
  {
    name: "Terminal Gold (wildcard)",
    note: "Bloomberg-adjacent — warm gray canvas with navy ink in light; near-black with gold highlights in dark",
    light: {
      background: "#f6f5f1",
      card: "#ffffff",
      primary: "#1e3a5f",
      "primary-foreground": "#ffffff",
      secondary: "#efeee8",
      muted: "#efeee8",
      "muted-foreground": "#6d6f66",
      accent: "#f5ecd0",
      "accent-foreground": "#705d1e",
      border: "#e8e6dd",
      input: "#e8e6dd",
      ring: "#b8962e",
      "chart-line": "#1e3a5f",
      "chart-fill": "rgba(30, 58, 95, 0.07)",
      "chart-grid": "#efede5",
    },
    dark: {
      ...cobaltDark,
      background: "#0d0d0b",
      card: "#161613",
      primary: "#e3b341",
      "primary-foreground": "#0d0d0b",
      "muted-foreground": "#9b9c8f",
      accent: "#2b2718",
      "accent-foreground": "#e9c766",
      border: "#31302a",
      input: "#31302a",
      ring: "#e3b341",
      "chart-line": "#e3b341",
      "chart-fill": "rgba(227, 179, 65, 0.09)",
      "chart-grid": "#232320",
    },
  },
  {
    name: "Volt (wildcard)",
    note: "Punchy tech — cool graphite canvas, chartreuse accent (dark-first)",
    light: {
      background: "#f4f6f4",
      card: "#ffffff",
      primary: "#4d7c0f",
      "primary-foreground": "#ffffff",
      secondary: "#eef1ec",
      muted: "#eef1ec",
      "muted-foreground": "#697268",
      accent: "#ecfccb",
      "accent-foreground": "#3f6212",
      border: "#e5eae2",
      input: "#e5eae2",
      ring: "#84cc16",
      "chart-line": "#4d7c0f",
      "chart-fill": "rgba(77, 124, 15, 0.08)",
      "chart-grid": "#edf1ea",
    },
    dark: {
      ...cobaltDark,
      background: "#0e100d",
      card: "#161a14",
      primary: "#a3e635",
      "primary-foreground": "#0e100d",
      "muted-foreground": "#98a494",
      accent: "#23301a",
      "accent-foreground": "#bef264",
      border: "#2b3427",
      input: "#2b3427",
      ring: "#a3e635",
      "chart-line": "#a3e635",
      "chart-fill": "rgba(163, 230, 53, 0.09)",
      "chart-grid": "#202920",
    },
  },
);

function block(selector: string, tokens: SchemeTokens): string {
  const lines = Object.entries(tokens)
    .map(([k, v]) => `  --${k}: ${v};`)
    .join("\n");
  return `${selector} {\n${lines}\n}`;
}

/* CSS for a scheme — injected into a <style> tag by the lab (so .dark still wins
   correctly), and what the "Copy CSS" button exports for globals.css. */
export function schemeCss(scheme: Scheme): string {
  return `${block(":root", scheme.light)}\n\n${block(".dark", scheme.dark)}`;
}
